# Generated by Django 4.2.30 on 2026-05-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_make_preview_image_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/'),
        ),
    ]
